name: Tests
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 10.x ]
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Use Nodejs
      uses: actions/setup-node@v1
    - name: Install node_modules
      run: npm install
    - name: Install ganache-cli
      run: npm -g install ganache-cli
    - name: Run ganache-cli
      run: ganache-cli -a 1 -i 5777 -m "abandon","ability","able","about","above","absent","absorb","abstract","absurd","abuse","access","accident" > /dev/null  &
    - name: Test contracts
      run: npm run test --network
